package local_test

import (
	"context"
	"errors"
	"math/rand/v2"
	"slices"
	"testing"

	"github.com/danielcbailey/Cookbook/core/models"
	"github.com/danielcbailey/Cookbook/pkg/database"
	"github.com/danielcbailey/Cookbook/pkg/database/local"
)

func setupRecipeTest(t *testing.T) (database.Transaction, models.User) {
	t.Helper()
	db, err := local.NewLocal(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	tx, err := db.NewTransaction(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { tx.Rollback() })

	u := testUser()
	if _, err := tx.CreateUser(&u); err != nil {
		t.Fatal(err)
	}
	return tx, u
}

func TestCreateRecipe_AssignsIDAndTimestamps(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	id, err := tx.CreateRecipe(&r)
	if err != nil {
		t.Fatal(err)
	}

	if id == 0 {
		t.Fatal("expected non-zero ID")
	}
	if r.ID != id {
		t.Fatalf("expected r.ID %d to match returned ID %d", r.ID, id)
	}
	if r.CreatedAt == 0 {
		t.Fatal("expected non-zero CreatedAt")
	}
	if r.UpdatedAt == 0 {
		t.Fatal("expected non-zero UpdatedAt")
	}
}

func TestGetRecipeByID_FullGraph(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	tx.CreateRecipe(&r)

	step := models.RecipeStep{
		RecipeID: r.ID,
		Index:    0,
		Title:    "Boil water",
		BodyText: "Bring water to a boil",
	}
	if _, err := tx.CreateOrUpdateRecipeStep(&step); err != nil {
		t.Fatal(err)
	}

	got, err := tx.GetRecipeByID(r.ID)
	if err != nil {
		t.Fatal(err)
	}
	if got.Title != "Pasta" {
		t.Fatalf("title: got %q, want %q", got.Title, "Pasta")
	}
	if len(got.Tags) != 2 {
		t.Fatalf("tags: got %d, want 2", len(got.Tags))
	}
	if len(got.Steps) != 1 {
		t.Fatalf("steps: got %d, want 1", len(got.Steps))
	}
}

func TestGetRecipeByID_NotFound(t *testing.T) {
	tx, _ := setupRecipeTest(t)

	_, err := tx.GetRecipeByID(999)
	if !errors.Is(err, database.ErrNotFound) {
		t.Fatalf("expected ErrNotFound, got %v", err)
	}
}

func TestGetRecipeByID_ReturnsCopy(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	tx.CreateRecipe(&r)

	got, _ := tx.GetRecipeByID(r.ID)
	got.Title = "mutated"
	got.Tags[0].Name = "mutated"

	got2, _ := tx.GetRecipeByID(r.ID)
	if got2.Title == "mutated" {
		t.Fatal("modifying returned recipe should not affect store")
	}
	if got2.Tags[0].Name == "mutated" {
		t.Fatal("modifying returned tags should not affect store")
	}
}

func TestUpdateRecipe_CoreFieldsOnly(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	tx.CreateRecipe(&r)

	step := models.RecipeStep{
		RecipeID: r.ID,
		Index:    0,
		Title:    "Step 1",
	}
	tx.CreateOrUpdateRecipeStep(&step)

	r.Title = "Updated Pasta"
	r.Steps = nil
	if err := tx.UpdateRecipe(&r); err != nil {
		t.Fatal(err)
	}

	got, _ := tx.GetRecipeByID(r.ID)
	if got.Title != "Updated Pasta" {
		t.Fatalf("title: got %q, want %q", got.Title, "Updated Pasta")
	}
	if len(got.Steps) != 1 {
		t.Fatal("UpdateRecipe should preserve existing steps")
	}
	if got.UpdatedAt < got.CreatedAt {
		t.Fatal("UpdatedAt should be >= CreatedAt")
	}
}

// testTotalTime and testNutrition are populated values used to prove both
// fields survive a write/read round trip.
func testTotalTime() models.RecipeTime {
	return models.RecipeTime{StartTime: 45, EndTime: 60, Unit: models.RecipeTimeUnitMinutes}
}

func testNutrition() models.RecipeNutrition {
	return models.RecipeNutrition{
		NutritionServings:    4,
		NutritionServingMass: 250,
		NutritionServingUnit: models.IngredientUnitGrams,
		IsAutogenerated:      true,
		Calories:             520,
		TotalFatGrams:        12.5,
		SaturatedFatGrams:    3.25,
		TransFatGrams:        0.5,
		CholestrolMilligrams: 30,
		SodiumMilligrams:     640,
		TotalCarbsGrams:      78.5,
		DietaryFiberGrams:    6,
		TotalSugarGrams:      4.5,
		ProteinGrams:         18.25,
	}
}

func TestCreateRecipe_StoresTotalTimeAndNutrition(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	r.TotalTime = testTotalTime()
	r.Nutrition = testNutrition()
	tx.CreateRecipe(&r)

	got, err := tx.GetRecipeByID(r.ID)
	if err != nil {
		t.Fatal(err)
	}
	if got.TotalTime != testTotalTime() {
		t.Fatalf("total time: got %+v, want %+v", got.TotalTime, testTotalTime())
	}
	if got.Nutrition != testNutrition() {
		t.Fatalf("nutrition: got %+v, want %+v", got.Nutrition, testNutrition())
	}
}

func TestUpdateRecipe_PersistsTotalTimeAndNutrition(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	r.TotalTime = testTotalTime()
	r.Nutrition = testNutrition()
	tx.CreateRecipe(&r)

	r.TotalTime = models.RecipeTime{StartTime: 2, EndTime: 3, Unit: models.RecipeTimeUnitHours}
	r.Nutrition.Calories = 610
	r.Nutrition.IsAutogenerated = false
	r.Nutrition.ProteinGrams = 22
	if err := tx.UpdateRecipe(&r); err != nil {
		t.Fatal(err)
	}

	got, err := tx.GetRecipeByID(r.ID)
	if err != nil {
		t.Fatal(err)
	}
	if got.TotalTime != r.TotalTime {
		t.Fatalf("total time: got %+v, want %+v", got.TotalTime, r.TotalTime)
	}
	if got.Nutrition != r.Nutrition {
		t.Fatalf("nutrition: got %+v, want %+v", got.Nutrition, r.Nutrition)
	}
}

func TestListRecipesByUserID_ListingShape(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	r.ImageURL = "recipes/1/img.jpg"
	r.TotalTime = testTotalTime()
	r.Nutrition = testNutrition()
	tx.CreateRecipe(&r)

	list, err := tx.ListRecipesByUserID(u.ID, 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(list) != 1 {
		t.Fatalf("recipes: got %d, want 1", len(list))
	}

	got := list[0]
	if got.ID != r.ID || got.UserID != u.ID {
		t.Fatalf("identity: got ID %d UserID %d, want %d/%d", got.ID, got.UserID, r.ID, u.ID)
	}
	if got.Title != "Pasta" {
		t.Fatalf("title: got %q, want %q", got.Title, "Pasta")
	}
	if got.ImageURL != "recipes/1/img.jpg" {
		t.Fatalf("image url: got %q", got.ImageURL)
	}
	if got.Servings != 4 {
		t.Fatalf("servings: got %d, want 4", got.Servings)
	}
	if got.Calories != testNutrition().Calories {
		t.Fatalf("calories: got %d, want %d", got.Calories, testNutrition().Calories)
	}
	if got.Time != testTotalTime() {
		t.Fatalf("time: got %+v, want %+v", got.Time, testTotalTime())
	}
	if len(got.Tags) != 2 {
		t.Fatalf("tags: got %d, want 2", len(got.Tags))
	}
}

func TestListRecipesByUserID_ReturnsCopiedTags(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	tx.CreateRecipe(&r)

	list, _ := tx.ListRecipesByUserID(u.ID, 0, 0)
	list[0].Tags[0].Name = "mutated"

	list2, _ := tx.ListRecipesByUserID(u.ID, 0, 0)
	if list2[0].Tags[0].Name == "mutated" {
		t.Fatal("modifying returned tags should not affect store")
	}
}

func TestListRecipesByUserID_Paging(t *testing.T) {
	tx, u := setupRecipeTest(t)

	// Created in one transaction, so these share a CreatedAt second and the
	// ordering falls through to the ID tie-break.
	const total = 5
	ids := make([]int64, total)
	for i := range total {
		r := testRecipe(u.ID)
		tx.CreateRecipe(&r)
		ids[i] = r.ID
	}

	all, err := tx.ListRecipesByUserID(u.ID, 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(all) != total {
		t.Fatalf("limit 0 should be unlimited: got %d, want %d", len(all), total)
	}
	// Newest first, so the highest ID leads.
	if all[0].ID != ids[total-1] {
		t.Fatalf("expected newest recipe %d first, got %d", ids[total-1], all[0].ID)
	}
	if all[total-1].ID != ids[0] {
		t.Fatalf("expected oldest recipe %d last, got %d", ids[0], all[total-1].ID)
	}

	// Pages must be disjoint and cover the whole set in order.
	var paged []int64
	for offset := 0; offset < total; offset += 2 {
		page, err := tx.ListRecipesByUserID(u.ID, offset, 2)
		if err != nil {
			t.Fatal(err)
		}
		for _, l := range page {
			paged = append(paged, l.ID)
		}
	}
	if len(paged) != total {
		t.Fatalf("paging covered %d recipes, want %d", len(paged), total)
	}
	for i, id := range paged {
		if id != all[i].ID {
			t.Fatalf("page %d: got recipe %d, want %d", i, id, all[i].ID)
		}
	}

	if page, _ := tx.ListRecipesByUserID(u.ID, total, 2); len(page) != 0 {
		t.Fatalf("offset past the end should be empty, got %d", len(page))
	}
	if page, _ := tx.ListRecipesByUserID(u.ID, -5, 2); len(page) != 2 || page[0].ID != all[0].ID {
		t.Fatal("negative offset should be clamped to 0")
	}
}

func TestDeleteRecipe(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	tx.CreateRecipe(&r)

	if err := tx.DeleteRecipe(r.ID); err != nil {
		t.Fatal(err)
	}
	_, err := tx.GetRecipeByID(r.ID)
	if !errors.Is(err, database.ErrNotFound) {
		t.Fatal("recipe should be deleted")
	}
}

func TestListRecipesByUserID_Order(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r1 := testRecipe(u.ID)
	r1.Title = "First"
	tx.CreateRecipe(&r1)

	r2 := testRecipe(u.ID)
	r2.Title = "Second"
	tx.CreateRecipe(&r2)

	list, err := tx.ListRecipesByUserID(u.ID, 0, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(list) != 2 {
		t.Fatalf("got %d recipes, want 2", len(list))
	}
	if list[0].Title != "Second" {
		t.Fatal("should be ordered by CreatedAt DESC (newest first)")
	}
	if len(list[0].Tags) == 0 {
		t.Fatal("list should include tags")
	}
}

func TestListRecipesByUserID_FiltersByUser(t *testing.T) {
	db, err := local.NewLocal(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	tx, _ := db.NewTransaction(t.Context())
	defer tx.Rollback()

	u1 := testUser()
	u1.Email = "a@test.com"
	tx.CreateUser(&u1)

	u2 := testUser()
	u2.Email = "b@test.com"
	tx.CreateUser(&u2)

	r1 := testRecipe(u1.ID)
	tx.CreateRecipe(&r1)

	r2 := testRecipe(u2.ID)
	tx.CreateRecipe(&r2)

	list, _ := tx.ListRecipesByUserID(u1.ID, 0, 0)
	if len(list) != 1 {
		t.Fatalf("got %d, want 1 recipe for user 1", len(list))
	}
}

func TestListRecipesBySemanticSimilarity(t *testing.T) {
	tx, u := setupRecipeTest(t)

	close := models.Recipe{
		UserID:    u.ID,
		Title:     "Close match",
		Embedding: []float32{1, 0, 0},
	}
	tx.CreateRecipe(&close)

	far := models.Recipe{
		UserID:    u.ID,
		Title:     "Far match",
		Embedding: []float32{0, 1, 0},
	}
	tx.CreateRecipe(&far)

	noEmbed := models.Recipe{
		UserID: u.ID,
		Title:  "No embedding",
	}
	tx.CreateRecipe(&noEmbed)

	query := []float32{1, 0.1, 0}
	results, err := tx.ListRecipesBySemanticSimilarity(u.ID, query, 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(results) != 2 {
		t.Fatalf("got %d, want 2 (recipes with embeddings only)", len(results))
	}
	if results[0].Title != "Close match" {
		t.Fatalf("closest should be first, got %q", results[0].Title)
	}
}

func TestListRecipesBySemanticSimilarity_Limit(t *testing.T) {
	tx, u := setupRecipeTest(t)

	for i := 0; i < 5; i++ {
		r := models.Recipe{
			UserID:    u.ID,
			Title:     "Recipe",
			Embedding: []float32{1, 0, 0},
		}
		tx.CreateRecipe(&r)
	}

	results, _ := tx.ListRecipesBySemanticSimilarity(u.ID, []float32{1, 0, 0}, 3)
	if len(results) != 3 {
		t.Fatalf("got %d, want 3", len(results))
	}

	unlimited, _ := tx.ListRecipesBySemanticSimilarity(u.ID, []float32{1, 0, 0}, 0)
	if len(unlimited) != 5 {
		t.Fatalf("limit 0 should be unlimited: got %d, want 5", len(unlimited))
	}
}

// setupFilterTest creates two users, gives user 1 three recipes spanning two
// categories/proteins/meals, and gives user 2 one recipe that shares user 1's
// values so the scoping assertions are meaningful.
func setupFilterTest(t *testing.T) (database.Transaction, models.User) {
	t.Helper()
	tx, u := setupRecipeTest(t)

	mk := func(userID int64, title, category, protein, meal string) {
		r := testRecipe(userID)
		r.Title = title
		r.Category = category
		r.Protein = protein
		r.SuggestedMeal = meal
		if _, err := tx.CreateRecipe(&r); err != nil {
			t.Fatal(err)
		}
	}

	mk(u.ID, "Roast", "roasts and braises", "beef", "dinner")
	mk(u.ID, "Stew", "soup and stew", "beef", "dinner")
	mk(u.ID, "Cake", "cake", "", "dessert")

	other := testUser()
	other.Email = "other@test.com"
	if _, err := tx.CreateUser(&other); err != nil {
		t.Fatal(err)
	}
	mk(other.ID, "Other Roast", "roasts and braises", "beef", "dinner")

	return tx, u
}

func TestListRecipesByCategory(t *testing.T) {
	tx, u := setupFilterTest(t)

	list, err := tx.ListRecipesByCategory(u.ID, "roasts and braises", 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(list) != 1 {
		t.Fatalf("got %d, want 1 (other users' recipes must be excluded)", len(list))
	}
	if list[0].Title != "Roast" {
		t.Fatalf("title: got %q, want %q", list[0].Title, "Roast")
	}

	if none, _ := tx.ListRecipesByCategory(u.ID, "pizza and flatbread", 0); len(none) != 0 {
		t.Fatalf("non-matching category: got %d, want 0", len(none))
	}
}

func TestListRecipesByProtein(t *testing.T) {
	tx, u := setupFilterTest(t)

	list, err := tx.ListRecipesByProtein(u.ID, "beef", 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(list) != 2 {
		t.Fatalf("got %d, want 2", len(list))
	}
	// Newest first: Stew was created after Roast.
	if list[0].Title != "Stew" {
		t.Fatalf("expected newest first, got %q", list[0].Title)
	}

	limited, _ := tx.ListRecipesByProtein(u.ID, "beef", 1)
	if len(limited) != 1 {
		t.Fatalf("limit: got %d, want 1", len(limited))
	}
}

func TestListRecipesByMeal(t *testing.T) {
	tx, u := setupFilterTest(t)

	list, err := tx.ListRecipesByMeal(u.ID, "dinner", 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(list) != 2 {
		t.Fatalf("got %d, want 2", len(list))
	}

	dessert, _ := tx.ListRecipesByMeal(u.ID, "dessert", 0)
	if len(dessert) != 1 || dessert[0].Title != "Cake" {
		t.Fatalf("dessert: got %+v", dessert)
	}
}

func TestListRecipesByTitleSearch(t *testing.T) {
	tx, u := setupFilterTest(t)

	titles := func(list []*models.RecipeListing) []string {
		out := make([]string, len(list))
		for i, l := range list {
			out[i] = l.Title
		}
		return out
	}

	cases := []struct {
		name  string
		query string
		limit int
		want  []string
	}{
		// The other user's "Other Roast" must never appear.
		{"exact, lowercased", "roast", 0, []string{"Roast"}},
		{"uppercased query", "ROAST", 0, []string{"Roast"}},
		{"matches mid-title, not just prefixes", "ew", 0, []string{"Stew"}},
		{"newest first", "a", 0, []string{"Cake", "Roast"}},
		{"limit applies after ordering", "a", 1, []string{"Cake"}},
		{"no match", "pizza", 0, nil},
		{"empty query matches everything", "", 0, []string{"Cake", "Stew", "Roast"}},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := tx.ListRecipesByTitleSearch(u.ID, tc.query, tc.limit)
			if err != nil {
				t.Fatal(err)
			}
			if !slices.Equal(titles(got), tc.want) {
				t.Fatalf("%q: got %v, want %v", tc.query, titles(got), tc.want)
			}
		})
	}
}

func TestListRecipeCategories(t *testing.T) {
	tx, u := setupFilterTest(t)

	got, err := tx.ListRecipeCategories(u.ID)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"cake", "roasts and braises", "soup and stew"}
	if !slices.Equal(got, want) {
		t.Fatalf("categories: got %v, want %v", got, want)
	}
}

func TestListRecipeProteins_DedupesAndSkipsEmpty(t *testing.T) {
	tx, u := setupFilterTest(t)

	got, err := tx.ListRecipeProteins(u.ID)
	if err != nil {
		t.Fatal(err)
	}
	// "beef" appears on two recipes and the cake has no protein at all.
	want := []string{"beef"}
	if !slices.Equal(got, want) {
		t.Fatalf("proteins: got %v, want %v", got, want)
	}
}

func TestListRecipeMealtimes(t *testing.T) {
	tx, u := setupFilterTest(t)

	got, err := tx.ListRecipeMealtimes(u.ID)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"dessert", "dinner"}
	if !slices.Equal(got, want) {
		t.Fatalf("mealtimes: got %v, want %v", got, want)
	}
}

func TestListRecipeTags(t *testing.T) {
	tx, u := setupFilterTest(t)

	// Every recipe from testRecipe carries the same two tags, so this also
	// covers de-duplication across a user's recipes. The second user's
	// identically named tags are separate rows and must not leak in.
	got, err := tx.ListRecipeTags(u.ID)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"italian", "quick"}
	if !slices.Equal(got, want) {
		t.Fatalf("tags: got %v, want %v", got, want)
	}
}

func TestListRecipesByTag(t *testing.T) {
	tx, u := setupFilterTest(t)

	got, err := tx.ListRecipesByTag(u.ID, "italian", 0)
	if err != nil {
		t.Fatal(err)
	}
	// All three of the user's recipes are tagged, but the other user's is not
	// visible even though it carries a tag of the same name.
	if len(got) != 3 {
		t.Fatalf("got %d listings, want 3", len(got))
	}

	none, err := tx.ListRecipesByTag(u.ID, "nonexistent", 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(none) != 0 {
		t.Fatalf("unknown tag: got %d listings, want 0", len(none))
	}
}

func TestListRecipeValues_EmptyForUnknownUser(t *testing.T) {
	tx, _ := setupFilterTest(t)

	for name, fn := range map[string]func(int64) ([]string, error){
		"categories": tx.ListRecipeCategories,
		"proteins":   tx.ListRecipeProteins,
		"mealtimes":  tx.ListRecipeMealtimes,
		"tags":       tx.ListRecipeTags,
	} {
		got, err := fn(99999)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if len(got) != 0 {
			t.Fatalf("%s: got %v, want empty", name, got)
		}
	}
}

// Every listing path must populate Tags, not just ListRecipesByUserID.
func TestListRecipes_AllPathsIncludeTags(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID) // has tags "italian" and "quick"
	r.Category = "cake"
	r.Protein = "beef"
	r.SuggestedMeal = "dinner"
	r.Embedding = []float32{1, 0, 0}
	tx.CreateRecipe(&r)

	paths := map[string]func() ([]*models.RecipeListing, error){
		"ByUserID": func() ([]*models.RecipeListing, error) { return tx.ListRecipesByUserID(u.ID, 0, 0) },
		"BySemanticSimilarity": func() ([]*models.RecipeListing, error) {
			return tx.ListRecipesBySemanticSimilarity(u.ID, []float32{1, 0, 0}, 0)
		},
		"ByCategory":    func() ([]*models.RecipeListing, error) { return tx.ListRecipesByCategory(u.ID, "cake", 0) },
		"ByProtein":     func() ([]*models.RecipeListing, error) { return tx.ListRecipesByProtein(u.ID, "beef", 0) },
		"ByMeal":        func() ([]*models.RecipeListing, error) { return tx.ListRecipesByMeal(u.ID, "dinner", 0) },
		"ByTag":         func() ([]*models.RecipeListing, error) { return tx.ListRecipesByTag(u.ID, "italian", 0) },
		"ByTitleSearch": func() ([]*models.RecipeListing, error) { return tx.ListRecipesByTitleSearch(u.ID, "past", 0) },
	}

	for name, list := range paths {
		got, err := list()
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if len(got) != 1 {
			t.Fatalf("%s: got %d listings, want 1", name, len(got))
		}
		if len(got[0].Tags) != 2 {
			t.Fatalf("%s: got %d tags, want 2", name, len(got[0].Tags))
		}
		for _, tag := range got[0].Tags {
			if tag.ID == 0 || tag.Name == "" {
				t.Fatalf("%s: tag not fully populated: %+v", name, tag)
			}
		}
	}
}

func TestCreateOrUpdateRecipeStep_Create(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	tx.CreateRecipe(&r)

	step := models.RecipeStep{
		RecipeID: r.ID,
		Index:    0,
		Title:    "Step one",
	}
	id, err := tx.CreateOrUpdateRecipeStep(&step)
	if err != nil {
		t.Fatal(err)
	}
	if id == 0 {
		t.Fatal("step should get an ID")
	}
	if step.ID != id {
		t.Fatalf("expected step.ID %d to match returned ID %d", step.ID, id)
	}

	got, _ := tx.GetRecipeByID(r.ID)
	if len(got.Steps) != 1 {
		t.Fatalf("steps: got %d, want 1", len(got.Steps))
	}
}

func TestCreateOrUpdateRecipeStep_Update(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	tx.CreateRecipe(&r)

	step := models.RecipeStep{RecipeID: r.ID, Index: 0, Title: "Original"}
	origID, err := tx.CreateOrUpdateRecipeStep(&step)
	if err != nil {
		t.Fatal(err)
	}

	step2 := models.RecipeStep{RecipeID: r.ID, Index: 0, Title: "Updated"}
	gotID, err := tx.CreateOrUpdateRecipeStep(&step2)
	if err != nil {
		t.Fatal(err)
	}

	if gotID != origID {
		t.Fatalf("upsert should reuse step ID: got %d, want %d", gotID, origID)
	}
	if step2.ID != gotID {
		t.Fatalf("expected step2.ID %d to match returned ID %d", step2.ID, gotID)
	}

	got, _ := tx.GetRecipeByID(r.ID)
	if len(got.Steps) != 1 {
		t.Fatalf("should still have 1 step, got %d", len(got.Steps))
	}
	if got.Steps[0].Title != "Updated" {
		t.Fatalf("title: got %q, want %q", got.Steps[0].Title, "Updated")
	}
}

func TestDeleteRecipeStep(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	tx.CreateRecipe(&r)

	s0 := models.RecipeStep{RecipeID: r.ID, Index: 0, Title: "Keep"}
	tx.CreateOrUpdateRecipeStep(&s0)
	s1 := models.RecipeStep{RecipeID: r.ID, Index: 1, Title: "Remove"}
	tx.CreateOrUpdateRecipeStep(&s1)

	if err := tx.DeleteRecipeStep(&s1); err != nil {
		t.Fatal(err)
	}

	got, _ := tx.GetRecipeByID(r.ID)
	if len(got.Steps) != 1 {
		t.Fatalf("steps: got %d, want 1", len(got.Steps))
	}
	if got.Steps[0].Title != "Keep" {
		t.Fatalf("wrong step kept: got %q", got.Steps[0].Title)
	}
}

func TestDeleteRecipeStep_ByIDWithoutRecipeID(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	tx.CreateRecipe(&r)

	step := models.RecipeStep{RecipeID: r.ID, Index: 0, Title: "Step"}
	tx.CreateOrUpdateRecipeStep(&step)

	orphanRef := &models.RecipeStep{ID: step.ID}
	if err := tx.DeleteRecipeStep(orphanRef); err != nil {
		t.Fatal(err)
	}

	got, _ := tx.GetRecipeByID(r.ID)
	if len(got.Steps) != 0 {
		t.Fatal("step should be deleted via ID scan")
	}
}

func TestTagReconciliation_Dedup(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r1 := testRecipe(u.ID)
	r1.Tags = []models.RecipeTag{{Name: "shared-tag"}}
	tx.CreateRecipe(&r1)

	r2 := testRecipe(u.ID)
	r2.Tags = []models.RecipeTag{{Name: "shared-tag"}}
	tx.CreateRecipe(&r2)

	got1, _ := tx.GetRecipeByID(r1.ID)
	got2, _ := tx.GetRecipeByID(r2.ID)

	if got1.Tags[0].ID != got2.Tags[0].ID {
		t.Fatalf("same tag name should get same ID: %d != %d", got1.Tags[0].ID, got2.Tags[0].ID)
	}
}

func TestTagReconciliation_UpdateReplacesTagSet(t *testing.T) {
	tx, u := setupRecipeTest(t)

	r := testRecipe(u.ID)
	r.Tags = []models.RecipeTag{{Name: "old"}}
	tx.CreateRecipe(&r)

	r.Tags = []models.RecipeTag{{Name: "new"}}
	tx.UpdateRecipe(&r)

	got, _ := tx.GetRecipeByID(r.ID)
	if len(got.Tags) != 1 {
		t.Fatalf("tags: got %d, want 1", len(got.Tags))
	}
	if got.Tags[0].Name != "new" {
		t.Fatalf("tag: got %q, want %q", got.Tags[0].Name, "new")
	}
}

func randEmbedding(rng *rand.Rand, dims int) []float32 {
	v := make([]float32, dims)
	for i := range v {
		v[i] = rng.Float32()*2 - 1
	}
	return v
}

func BenchmarkListRecipesBySemanticSimilarity_1000(b *testing.B) {
	const numRecipes = 1000
	const dims = 1536

	db, err := local.NewLocal(b.TempDir())
	if err != nil {
		b.Fatal(err)
	}

	tx, err := db.NewTransaction(context.Background())
	if err != nil {
		b.Fatal(err)
	}

	u := models.User{Email: "bench@test.com", PasswordHash: "h"}
	if _, err := tx.CreateUser(&u); err != nil {
		b.Fatal(err)
	}

	rng := rand.New(rand.NewPCG(42, 0))
	for i := 0; i < numRecipes; i++ {
		r := models.Recipe{
			UserID:    u.ID,
			Title:     "Recipe",
			Embedding: randEmbedding(rng, dims),
		}
		if _, err := tx.CreateRecipe(&r); err != nil {
			b.Fatal(err)
		}
	}

	if err := tx.Commit(); err != nil {
		b.Fatal(err)
	}

	query := randEmbedding(rng, dims)

	b.ResetTimer()
	for b.Loop() {
		tx, err := db.NewTransaction(context.Background())
		if err != nil {
			b.Fatal(err)
		}
		results, err := tx.ListRecipesBySemanticSimilarity(u.ID, query, 10)
		if err != nil {
			b.Fatal(err)
		}
		if len(results) != 10 {
			b.Fatalf("got %d results, want 10", len(results))
		}
		tx.Rollback()
	}
}
