// Command enumgen generates, for every string-style enum in a package, a slice
// of its declared values and an IsValid method, so callers can check a value
// without hand-maintaining a list that drifts as constants are added.
//
// An enum here is any type declared in the package that has at least one
// package-level constant declared with that type. Values keep their
// declaration order (files sorted by name, then source order).
//
// It is meant to be driven by go:generate, which runs it in the directory of
// the file holding the directive:
//
//	//go:generate go run github.com/danielcbailey/Cookbook/tools/enumgen -output=enums_gen.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	log.SetFlags(0)
	log.SetPrefix("enumgen: ")

	dir := flag.String("dir", ".", "directory of the package to scan")
	output := flag.String("output", "enums_gen.go", "generated file, written into -dir")
	typeList := flag.String("type", "", "comma-separated type names; defaults to every enum type found")
	flag.Parse()

	only := map[string]bool{}
	for name := range strings.SplitSeq(*typeList, ",") {
		if name = strings.TrimSpace(name); name != "" {
			only[name] = true
		}
	}

	pkgName, enums, err := scan(*dir, *output)
	if err != nil {
		log.Fatal(err)
	}

	if len(only) > 0 {
		var kept []enum
		for _, e := range enums {
			if only[e.typeName] {
				kept = append(kept, e)
				delete(only, e.typeName)
			}
		}
		for name := range only {
			log.Fatalf("no constants declared with type %s in %s", name, *dir)
		}
		enums = kept
	}

	if len(enums) == 0 {
		log.Fatalf("no enum types found in %s", *dir)
	}

	src, err := render(pkgName, enums)
	if err != nil {
		log.Fatal(err)
	}

	path := filepath.Join(*dir, *output)
	if err := os.WriteFile(path, src, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s (%d types)\n", path, len(enums))
}

// enum is one type together with the constants declared with it.
type enum struct {
	typeName string
	consts   []string
}

// scan parses the package in dir and returns its name along with every type
// that is both declared there and used as the type of at least one constant.
// The file named by output is ignored so a rerun does not feed on itself.
func scan(dir, output string) (string, []enum, error) {
	// Sort the paths so the output only changes when the source does.
	paths, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return "", nil, err
	}
	sort.Strings(paths)

	fset := token.NewFileSet()
	var files []*ast.File
	var pkgName string

	for _, path := range paths {
		base := filepath.Base(path)
		if base == output || strings.HasSuffix(base, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return "", nil, err
		}
		if pkgName == "" {
			pkgName = file.Name.Name
		} else if pkgName != file.Name.Name {
			return "", nil, fmt.Errorf("%s: package %s, but %s was seen first", path, file.Name.Name, pkgName)
		}
		files = append(files, file)
	}
	if len(files) == 0 {
		return "", nil, fmt.Errorf("no Go files in %s", dir)
	}

	declared := map[string]bool{}
	consts := map[string][]string{}
	var order []string

	for _, file := range files {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, spec := range gen.Specs {
				switch spec := spec.(type) {
				case *ast.TypeSpec:
					declared[spec.Name.Name] = true
				case *ast.ValueSpec:
					if gen.Tok != token.CONST {
						continue
					}
					ident, ok := spec.Type.(*ast.Ident)
					if !ok {
						continue
					}
					for _, n := range spec.Names {
						if n.Name == "_" {
							continue
						}
						if _, seen := consts[ident.Name]; !seen {
							order = append(order, ident.Name)
						}
						consts[ident.Name] = append(consts[ident.Name], n.Name)
					}
				}
			}
		}
	}

	var enums []enum
	for _, typeName := range order {
		// Constants typed by an import or a builtin are not this package's enums.
		if !declared[typeName] {
			continue
		}
		enums = append(enums, enum{typeName: typeName, consts: consts[typeName]})
	}
	return pkgName, enums, nil
}

func render(pkgName string, enums []enum) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by tools/enumgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n", pkgName)

	for _, e := range enums {
		fmt.Fprintf(&buf, "\n// %sValues holds every declared %s, in declaration order.\n", e.typeName, e.typeName)
		fmt.Fprintf(&buf, "var %sValues = []%s{\n", e.typeName, e.typeName)
		for _, name := range e.consts {
			fmt.Fprintf(&buf, "\t%s,\n", name)
		}
		fmt.Fprintf(&buf, "}\n")

		fmt.Fprintf(&buf, "\n// IsValid reports whether v is one of %sValues.\n", e.typeName)
		fmt.Fprintf(&buf, "func (v %s) IsValid() bool {\n", e.typeName)
		fmt.Fprintf(&buf, "\tswitch v {\n\tcase ")
		for i, name := range e.consts {
			if i > 0 {
				fmt.Fprintf(&buf, ",\n\t\t")
			}
			fmt.Fprintf(&buf, "%s", name)
		}
		fmt.Fprintf(&buf, ":\n\t\treturn true\n\t}\n\treturn false\n}\n")
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w\n%s", err, buf.String())
	}
	return src, nil
}
