package models

import (
	"fmt"
	"strconv"
	"strings"
)

type RecipeTag struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

type RecipeTime struct {
	StartTime float32        `json:"start_time"`
	EndTime   float32        `json:"end_time,omitempty"`
	Unit      RecipeTimeUnit `json:"unit"`
}

type RecipeIngredient struct {
	ID         int64          `json:"id"`
	RecipeID   int64          `json:"-"`
	Ingredient Ingredient     `json:"ingredient"`
	Quantity   float32        `json:"quantity"`
	Unit       IngredientUnit `json:"unit"`
	rawString  string         `json:"-"`
}

type RecipeStep struct {
	ID       int64  `json:"id"`
	RecipeID int64  `json:"-"`
	Index    int    `json:"-"`
	Title    string `json:"title"`
	ImageURL string `json:"image_url"`
	BodyText string `json:"body_text"` // contains references to ingredients/times in the format of {{ingr-idx}} and {{time-idx}}
}

type Recipe struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	ImageURL    string             `json:"image_url"`
	Author      string             `json:"author"`
	Publisher   string             `json:"publisher"`
	Servings    int                `json:"servings"`
	Steps       []RecipeStep       `json:"steps"`
	TotalTime   RecipeTime         `json:"total_time"`
	Nutrition   RecipeNutrition    `json:"nutrition"`
	Ingredients []RecipeIngredient `json:"ingredients"`

	Category      string      `json:"category"`
	Protein       string      `json:"protein"`
	Cuisine       string      `json:"cuisine"`
	SuggestedMeal string      `json:"suggested_meal"`
	Tags          []RecipeTag `json:"tags"`
	Embedding     []float32   `json:"embedding,omitempty"`
	CreatedAt     int64       `json:"created_at"`
	UpdatedAt     int64       `json:"updated_at"`
}

type RecipeNutrition struct {
	NutritionServings    float32        `json:"servings"`
	NutritionServingMass float32        `json:"serving_mass"`
	NutritionServingUnit IngredientUnit `json:"serving_mass_unit"`
	IsAutogenerated      bool           `json:"is_auto_generated"`
	Calories             int            `json:"calories"`
	TotalFatGrams        float32        `json:"total_fat_grams"`
	SaturatedFatGrams    float32        `json:"saturated_fat_grams"`
	TransFatGrams        float32        `json:"trans_fat_grams"`
	CholestrolMilligrams float32        `json:"cholestrol_mg"`
	SodiumMilligrams     float32        `json:"sodium_mg"`
	TotalCarbsGrams      float32        `json:"total_carbs_grams"`
	DietaryFiberGrams    float32        `json:"dietary_fiber_grams"`
	TotalSugarGrams      float32        `json:"total_sugar_grams"`
	ProteinGrams         float32        `json:"protein_grams"`
}

type RecipeListing struct {
	ID       int64       `json:"id"`
	UserID   int64       `json:"user_id"`
	Title    string      `json:"title"`
	ImageURL string      `json:"image_url"`
	Servings int         `json:"servings"`
	Calories int         `json:"calories"`
	Time     RecipeTime  `json:"time"`
	Tags     []RecipeTag `json:"tags"`
}

type RecipeTimeUnit string

const (
	RecipeTimeUnitSeconds RecipeTimeUnit = "second"
	RecipeTimeUnitMinutes RecipeTimeUnit = "minute"
	RecipeTimeUnitHours   RecipeTimeUnit = "hour"
	RecipeTimeUnitDays    RecipeTimeUnit = "day"
	RecipeTimeUnitWeeks   RecipeTimeUnit = "week"
)

type RecipeMealtime string

const (
	RecipeMealtimeBreakfast RecipeMealtime = "breakfast"
	RecipeMealtimeLunch     RecipeMealtime = "lunch"
	RecipeMealtimeDinner    RecipeMealtime = "dinner"
	RecipeMealtimeDessert   RecipeMealtime = "dessert"
	RecipeMealtimeSnack     RecipeMealtime = "snack"
)

type RecipeCategory string

const (
	RecipeCategoryBread                   RecipeCategory = "bread"
	RecipeCategoryPastry                  RecipeCategory = "pastry"
	RecipeCategoryMuffin                  RecipeCategory = "muffin"
	RecipeCategoryScone                   RecipeCategory = "scone"
	RecipeCategoryCake                    RecipeCategory = "cake"
	RecipeCategoryPie                     RecipeCategory = "pie"
	RecipeCategoryDessertBar              RecipeCategory = "dessert bar"
	RecipeCategoryFrozenAndColdDessert    RecipeCategory = "frozen and cold dessert"
	RecipeCategoryCookie                  RecipeCategory = "cookie"
	RecipeCategoryBatterBread             RecipeCategory = "batter bread"
	RecipeCategoryPastaAndNoodles         RecipeCategory = "pasta and noodles"
	RecipeCategorySoupAndStew             RecipeCategory = "soup and stew"
	RecipeCategorySalad                   RecipeCategory = "salad"
	RecipeCategorySandwichAndWraps        RecipeCategory = "sandwich and wraps"
	RecipeCategoryRice                    RecipeCategory = "rice"
	RecipeCategoryGrilled                 RecipeCategory = "grilled"
	RecipeCategoryRoastsAndBraises        RecipeCategory = "roasts and braises"
	RecipeCategoryFriedFood               RecipeCategory = "fried food"
	RecipeCategoryStirFryAndSaute         RecipeCategory = "stir-fry and saute"
	RecipeCategoryCasseroleAndBakes       RecipeCategory = "casserole and bakes"
	RecipeCategoryPizzaAndFlatbread       RecipeCategory = "pizza and flatbread"
	RecipeCategorySeafood                 RecipeCategory = "seafood"
	RecipeCategoryEggs                    RecipeCategory = "eggs"
	RecipeCategorySavoryBreakfast         RecipeCategory = "savory breakfast"
	RecipeCategoryCurry                   RecipeCategory = "curry"
	RecipeCategoryDumplingsAndFilledPasta RecipeCategory = "dumplings and filled pasta"
)

type RecipeCuisine string

const (
	RecipeCuisineAmerican       RecipeCuisine = "american"
	RecipeCuisineGerman         RecipeCuisine = "german"
	RecipeCuisineFrench         RecipeCuisine = "french"
	RecipeCuisineMexican        RecipeCuisine = "mexican"
	RecipeCuisineLatinAmerican  RecipeCuisine = "latin american"
	RecipeCuisineItalian        RecipeCuisine = "italian"
	RecipeCuisineJapanese       RecipeCuisine = "japanese"
	RecipeCuisineChinese        RecipeCuisine = "chinese"
	RecipeCuisineKorean         RecipeCuisine = "korean"
	RecipeCuisineMiddleEastern  RecipeCuisine = "middle eastern"
	RecipeCuisineIndian         RecipeCuisine = "indian"
	RecipeCuisineThai           RecipeCuisine = "thai"
	RecipeCuisineMediterranean  RecipeCuisine = "mediterranean"
	RecipeCuisineSpanish        RecipeCuisine = "spanish"
	RecipeCuisineCaribbean      RecipeCuisine = "caribbean"
	RecipeCuisineVietnamese     RecipeCuisine = "vietnamese"
	RecipeCuisineAfrican        RecipeCuisine = "african"
	RecipeCuisineBritish        RecipeCuisine = "british"
	RecipeCuisineSoutheastAsian RecipeCuisine = "southeast asian"
	RecipeCuisineFusion         RecipeCuisine = "fusion"
	RecipeCuisineOther          RecipeCuisine = "other"
)

type RecipeProtein string

const (
	RecipeProteinChicken    RecipeProtein = "chicken"
	RecipeProteinPork       RecipeProtein = "pork"
	RecipeProteinBeef       RecipeProtein = "beef"
	RecipeProteinVeal       RecipeProtein = "veal"
	RecipeProteinLamb       RecipeProtein = "lamb"
	RecipeProteinDuck       RecipeProtein = "duck"
	RecipeProteinTurkey     RecipeProtein = "turkey"
	RecipeProteinSausage    RecipeProtein = "sausage"
	RecipeProteinRedMeat    RecipeProtein = "red meat"
	RecipeProteinPoultry    RecipeProtein = "poultry"
	RecipeProteinGameMeat   RecipeProtein = "game meat"
	RecipeProteinOffal      RecipeProtein = "offal"
	RecipeProteinShrimp     RecipeProtein = "shrimp"
	RecipeProteinSalmon     RecipeProtein = "salmon"
	RecipeProteinTuna       RecipeProtein = "tuna"
	RecipeProteinCod        RecipeProtein = "cod"
	RecipeProteinCrab       RecipeProtein = "crab"
	RecipeProteinHalibut    RecipeProtein = "halibut"
	RecipeProteinLobster    RecipeProtein = "lobster"
	RecipeProteinWhitefish  RecipeProtein = "whitefish"
	RecipeProteinOilyFish   RecipeProtein = "oily fish"
	RecipeProteinCrustacean RecipeProtein = "crustacean"
	RecipeProteinMollusk    RecipeProtein = "mollusk"
)

func RecipeIngredientString(ri RecipeIngredient) string {
	return fmt.Sprintf("{i:%g,%s,%s}", ri.Quantity, ri.Unit, ri.Ingredient.Name)
}

func RecipeTimeString(rt RecipeTime) string {
	if rt.EndTime > 0 {
		return fmt.Sprintf("{t:%g-%g,%s}", rt.StartTime, rt.EndTime, rt.Unit)
	} else {
		return fmt.Sprintf("{t:%g,%s}", rt.StartTime, rt.Unit)
	}
}

func GetRecipeStepIngredients(step RecipeStep) []RecipeIngredient {
	var ingredients []RecipeIngredient

	split := splitStepBody(step.BodyText)
	for _, part := range split {
		if strings.HasPrefix(part, "{i:") && strings.HasSuffix(part, "}") {
			threeParts := strings.SplitN(part[3:len(part)-1], ",", 3)
			if len(threeParts) != 3 {
				continue
			}

			var ingr RecipeIngredient
			qty, err := strconv.ParseFloat(threeParts[0], 32)
			if err != nil {
				continue
			}

			ingr.Quantity = float32(qty)
			ingr.Unit = IngredientUnit(threeParts[1])
			ingr.Ingredient = Ingredient{Name: threeParts[2]}
			ingr.rawString = part

			ingredients = append(ingredients, ingr)
		}
	}

	return ingredients
}

func (ri RecipeIngredient) Replace(step *RecipeStep, newIngr RecipeIngredient) {
	newStr := RecipeIngredientString(newIngr)
	step.BodyText = strings.Replace(step.BodyText, ri.rawString, newStr, 1)
}

func splitStepBody(body string) []string {
	ret := []string{}
	workingPortion := strings.Builder{}
	depth := 0
	for i := 0; i < len(body); i++ {
		c := body[i]
		if c == '{' {
			if depth == 0 {
				if workingPortion.Len() > 0 {
					ret = append(ret, workingPortion.String())
					workingPortion.Reset()
				}
			}
			depth++
		} else if c == '}' {
			depth--
			if depth <= 0 {
				depth = 0
				workingPortion.WriteByte(c)
				ret = append(ret, workingPortion.String())
				workingPortion.Reset()
				continue
			}
		}
		workingPortion.WriteByte(c)
	}

	if workingPortion.Len() > 0 {
		ret = append(ret, workingPortion.String())
	}

	return ret
}
