package models

type RecipeTag struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

type RecipeTime struct {
	StepID    int64          `json:"step_id,omitempty"`
	Index     int            `json:"index"`
	StartTime float32        `json:"start_time"`
	EndTime   float32        `json:"end_time,omitempty"`
	Unit      RecipeTimeUnit `json:"unit"`
}

type RecipeIngredient struct {
	ID         int64          `json:"id"`
	StepID     int64          `json:"step_id,omitempty"`
	Index      int            `json:"index"`
	Ingredient Ingredient     `json:"ingredient"`
	Quantity   float32        `json:"quantity"`
	Unit       IngredientUnit `json:"unit"`
}

type RecipeStep struct {
	ID          int64              `json:"id"`
	RecipeID    int64              `json:"omit"`
	Index       int                `json:"index"`
	Title       string             `json:"title"`
	ImageURL    string             `json:"image_url"`
	BodyText    string             `json:"body_text"` // contains references to ingredients/times in the format of {{ingr-idx}} and {{time-idx}}
	Ingredients []RecipeIngredient `json:"ingredients"`
	Times       []RecipeTime       `json:"times"`
}

type Recipe struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	ImageURL    string             `json:"image_url"`
	Author      string             `json:"author"`
	Publisher   string             `json:"publisher"`
	Servings    int                `json:"servings"`
	Ingredients []RecipeIngredient `json:"ingredients"`
	Steps       []RecipeStep       `json:"steps"`
	TotalTime   RecipeTime         `json:"total_time"`
	Nutrition   RecipeNutrition    `json:"nutrition"`

	Category      string      `json:"category"`
	Protein       string      `json:"protein"`
	Cuisine       string      `json:"cuisine"`
	SuggestedMeal string      `json:"suggested_meal"`
	Tags          []RecipeTag `json:"tags"`
	Embedding     []float32   `json:"embedding,omitempty"`
	CreatedAt     int64       `json:"created_at"`
	UpdatedAt     int64       `json:"updated_at"`
}

type RecipeNutrition struct {
	NutritionServings    float32        `json:"servings"`
	NutritionServingMass float32        `json:"serving_mass"`
	NutritionServingUnit IngredientUnit `json:"serving_mass_unit"`
	IsAutogenerated      bool           `json:"is_auto_generated"`
	Calories             int            `json:"calories"`
	TotalFatGrams        float32        `json:"total_fat_grams"`
	SaturatedFatGrams    float32        `json:"saturated_fat_grams"`
	TransFatGrams        float32        `json:"trans_fat_grams"`
	CholestrolMilligrams float32        `json:"cholestrol_mg"`
	SodiumMilligrams     float32        `json:"sodium_mg"`
	TotalCarbsGrams      float32        `json:"total_carbs_grams"`
	DietaryFiberGrams    float32        `json:"dietary_fiber_grams"`
	TotalSugarGrams      float32        `json:"total_sugar_grams"`
	ProteinGrams         float32        `json:"protein_grams"`
}

type RecipeListing struct {
	ID       int64
	UserID   int64
	Title    string
	ImageURL string
}

type RecipeTimeUnit string

const (
	RecipeTimeUnitSeconds RecipeTimeUnit = "second"
	RecipeTimeUnitMinutes RecipeTimeUnit = "minute"
	RecipeTimeUnitHours   RecipeTimeUnit = "hour"
	RecipeTimeUnitDays    RecipeTimeUnit = "day"
	RecipeTimeUnitWeeks   RecipeTimeUnit = "week"
)
